
(function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){"use strict";require('./masonry');var options={sourceAttr:'href',overlay:true,captions:false,showCounter:false,animationSpeed:150,loop:false,rel:false,className:'lightbox-gallery',widthRatio:0.9,heightRatio:0.8,doubleTapZoom:2,maxZoom:10,htmlClass:'has-lightbox'};jQuery(function($){var gal=$('.wp-block-gallery a').simpleLightbox(options);});},{"./masonry":2}],2:[function(require,module,exports){"use strict";function _toConsumableArray(arr){return _arrayWithoutHoles(arr)||_iterableToArray(arr)||_nonIterableSpread();}
function _nonIterableSpread(){throw new TypeError("Invalid attempt to spread non-iterable instance");}
function _iterableToArray(iter){if(Symbol.iterator in Object(iter)||Object.prototype.toString.call(iter)==="[object Arguments]")return Array.from(iter);}
function _arrayWithoutHoles(arr){if(Array.isArray(arr)){for(var i=0,arr2=new Array(arr.length);i<arr.length;i++){arr2[i]=arr[i];}return arr2;}}
var masonryLayout=function masonryLayout(containerElem,columns){var initialColumns=columns;var md=window.matchMedia('(min-width : 768px) and (max-width : 992px)');var masonryElem=document.querySelector(".".concat(containerElem))||document.querySelector("#".concat(containerElem));if(masonryElem!==null){var WidthChange=function WidthChange(mq){mq.matches?columns=2:columns=initialColumns;masonryColumnClass(columns);addColumns(masonryElem,columns,columnsElements);addChilds(childs,columns,columnsElements);removeEmptyChilds(masonryElem,columns);};var childs=_toConsumableArray(masonryElem.children);var columnsElements=[];childs.map(function(child){if(!child.classList.contains('masonry-item')){child.classList.add('masonry-item');}});md.addListener(WidthChange);WidthChange(md);}
function masonryColumnClass(cols){removeClassByPrefix(masonryElem,'columns-');masonryElem.classList.add('masonry-layout',"columns-".concat(cols));}
function removeClassByPrefix(el,prefix){var regx=new RegExp('\\b'+prefix+'.*?\\b','g');el.className=el.className.replace(regx,'');return el;}
function addColumns(el,cols,colsEl){for(var i=1;i<=cols;i++){var column=document.createElement('div');column.classList.add('masonry-column',"column-".concat(i));el.appendChild(column);colsEl.push(column);}}
function addChilds(childItems,cols,colsEl){for(var m=0;m<Math.ceil(childItems.length/cols);m++){for(var n=0;n<cols;n++){var item=childItems[m*cols+n];if(item!=null){colsEl[n].appendChild(item);}}}}
function removeEmptyChilds(containerEl,columns){var childs=_toConsumableArray(containerEl.children);for(var i=0;i<childs.length;i++){if(i>columns){childs[i].remove();}}}};masonryLayout('masonry',3);},{}]},{},[1]);